apiVersion: v1
data:
  policy.cfg: |-
    {
      "kind": "Policy",
      "apiVersion": "v1",
      "extenders": [
        {
          "urlPrefix": "http://stork-service.kube-system:8099",
          "apiVersion": "v1beta1",
          "filterVerb": "filter",
          "prioritizeVerb": "prioritize",
          "weight": 5,
          "enableHttps": false,
          "nodeCacheCapable": false
        }
      ]
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"policy.cfg":"{\n  \"kind\": \"Policy\",\n  \"apiVersion\": \"v1\",\n  \"extenders\": [\n    {\n      \"urlPrefix\": \"http://stork-service.kube-system:8099\",\n      \"apiVersion\": \"v1beta1\",\n      \"filterVerb\": \"filter\",\n      \"prioritizeVerb\": \"prioritize\",\n      \"weight\": 5,\n      \"enableHttps\": false,\n      \"nodeCacheCapable\": false\n    }\n  ]\n}"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"stork-config","namespace":"kube-system"}}
  creationTimestamp: null
  name: stork-config
  selfLink: /api/v1/namespaces/kube-system/configmaps/stork-config
