apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","k8s-app":"dns-autoscaler","kubernetes.io/cluster-service":"true"},"name":"dns-autoscaler","namespace":"kube-system"},"spec":{"selector":{"matchLabels":{"k8s-app":"dns-autoscaler"}},"template":{"metadata":{"annotations":{"scheduler.alpha.kubernetes.io/critical-pod":"","seccomp.security.alpha.kubernetes.io/pod":"docker/default"},"labels":{"k8s-app":"dns-autoscaler"}},"spec":{"affinity":{"nodeAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"preference":{"matchExpressions":[{"key":"node-role.kubernetes.io/master","operator":"In","values":[""]}]},"weight":100}]},"podAntiAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":[{"labelSelector":{"matchLabels":{"k8s-app":"dns-autoscaler"}},"topologyKey":"kubernetes.io/hostname"}]}},"containers":[{"command":["/cluster-proportional-autoscaler","--namespace=kube-system","--default-params={\"linear\":{\"preventSinglePointFailure\":true,\"coresPerReplica\":256,\"nodesPerReplica\":16,\"min\":2}}","--logtostderr=true","--v=2","--configmap=dns-autoscaler","--target=Deployment/coredns"],"image":"k8s.gcr.io/cluster-proportional-autoscaler-amd64:1.6.0","name":"autoscaler","resources":{"requests":{"cpu":"20m","memory":"10Mi"}}}],"nodeSelector":{"beta.kubernetes.io/os":"linux"},"priorityClassName":"system-cluster-critical","securityContext":{"fsGroup":65534,"supplementalGroups":[65534]},"serviceAccountName":"dns-autoscaler","tolerations":[{"effect":"NoSchedule","key":"node-role.kubernetes.io/master","operator":"Equal"},{"key":"CriticalAddonsOnly","operator":"Exists"}]}}}}
  creationTimestamp: null
  generation: 1
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: dns-autoscaler
    kubernetes.io/cluster-service: "true"
  name: dns-autoscaler
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/dns-autoscaler
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: dns-autoscaler
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
        seccomp.security.alpha.kubernetes.io/pod: docker/default
      creationTimestamp: null
      labels:
        k8s-app: dns-autoscaler
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: In
                values:
                - ""
            weight: 100
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                k8s-app: dns-autoscaler
            topologyKey: kubernetes.io/hostname
      containers:
      - command:
        - /cluster-proportional-autoscaler
        - --namespace=kube-system
        - --default-params={"linear":{"preventSinglePointFailure":true,"coresPerReplica":256,"nodesPerReplica":16,"min":2}}
        - --logtostderr=true
        - --v=2
        - --configmap=dns-autoscaler
        - --target=Deployment/coredns
        image: k8s.gcr.io/cluster-proportional-autoscaler-amd64:1.6.0
        imagePullPolicy: IfNotPresent
        name: autoscaler
        resources:
          requests:
            cpu: 20m
            memory: 10Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        beta.kubernetes.io/os: linux
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 65534
        supplementalGroups:
        - 65534
      serviceAccount: dns-autoscaler
      serviceAccountName: dns-autoscaler
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Equal
      - key: CriticalAddonsOnly
        operator: Exists
status: {}
