apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"component":"scheduler","name":"stork-scheduler","tier":"control-plane"},"name":"stork-scheduler","namespace":"kube-system"},"spec":{"replicas":3,"template":{"metadata":{"labels":{"component":"scheduler","tier":"control-plane"},"name":"stork-scheduler"},"spec":{"affinity":{"podAntiAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":[{"labelSelector":{"matchExpressions":[{"key":"name","operator":"In","values":["stork-scheduler"]}]},"topologyKey":"kubernetes.io/hostname"}]}},"containers":[{"command":["/usr/local/bin/kube-scheduler","--address=0.0.0.0","--leader-elect=true","--scheduler-name=stork","--policy-configmap=stork-config","--policy-configmap-namespace=kube-system","--lock-object-name=stork-scheduler"],"image":"gcr.io/google_containers/kube-scheduler-amd64:v1.13.5","livenessProbe":{"httpGet":{"path":"/healthz","port":10251},"initialDelaySeconds":15},"name":"stork-scheduler","readinessProbe":{"httpGet":{"path":"/healthz","port":10251}},"resources":{"requests":{"cpu":"0.1"}}}],"hostPID":false,"serviceAccountName":"stork-scheduler-account"}}}}
  creationTimestamp: null
  generation: 1
  labels:
    component: scheduler
    name: stork-scheduler
    tier: control-plane
  name: stork-scheduler
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/stork-scheduler
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      component: scheduler
      tier: control-plane
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: scheduler
        tier: control-plane
      name: stork-scheduler
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - stork-scheduler
            topologyKey: kubernetes.io/hostname
      containers:
      - command:
        - /usr/local/bin/kube-scheduler
        - --address=0.0.0.0
        - --leader-elect=true
        - --scheduler-name=stork
        - --policy-configmap=stork-config
        - --policy-configmap-namespace=kube-system
        - --lock-object-name=stork-scheduler
        image: gcr.io/google_containers/kube-scheduler-amd64:v1.13.5
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10251
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: stork-scheduler
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10251
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: stork-scheduler-account
      serviceAccountName: stork-scheduler-account
      terminationGracePeriodSeconds: 30
status: {}
