apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"helm","name":"tiller"},"name":"tiller-deploy","namespace":"kube-system"},"spec":{"replicas":1,"strategy":{},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"helm","name":"tiller"}},"spec":{"automountServiceAccountToken":true,"containers":[{"env":[{"name":"TILLER_NAMESPACE","value":"kube-system"},{"name":"TILLER_HISTORY_MAX","value":"0"}],"image":"gcr.io/kubernetes-helm/tiller:v2.13.1","imagePullPolicy":"IfNotPresent","livenessProbe":{"httpGet":{"path":"/liveness","port":44135},"initialDelaySeconds":1,"timeoutSeconds":1},"name":"tiller","ports":[{"containerPort":44134,"name":"tiller"},{"containerPort":44135,"name":"http"}],"readinessProbe":{"httpGet":{"path":"/readiness","port":44135},"initialDelaySeconds":1,"timeoutSeconds":1},"resources":{}}],"priorityClassName":"system-cluster-critical","serviceAccountName":"tiller"}}},"status":{}}
  creationTimestamp: null
  generation: 1
  labels:
    app: helm
    name: tiller
  name: tiller-deploy
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/tiller-deploy
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: helm
      name: tiller
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helm
        name: tiller
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        - name: TILLER_NAMESPACE
          value: kube-system
        - name: TILLER_HISTORY_MAX
          value: "0"
        image: gcr.io/kubernetes-helm/tiller:v2.13.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /liveness
            port: 44135
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: tiller
        ports:
        - containerPort: 44134
          name: tiller
          protocol: TCP
        - containerPort: 44135
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readiness
            port: 44135
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: tiller
      serviceAccountName: tiller
      terminationGracePeriodSeconds: 30
status: {}
