apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"scheduler.alpha.kubernetes.io/critical-pod":""},"labels":{"tier":"control-plane"},"name":"stork","namespace":"kube-system"},"spec":{"replicas":3,"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"scheduler.alpha.kubernetes.io/critical-pod":""},"labels":{"name":"stork","tier":"control-plane"}},"spec":{"affinity":{"podAntiAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":[{"labelSelector":{"matchExpressions":[{"key":"name","operator":"In","values":["stork"]}]},"topologyKey":"kubernetes.io/hostname"}]}},"containers":[{"command":["/stork","--driver=pxd","--verbose","--leader-elect=true","--health-monitor-interval=120"],"image":"openstorage/stork:2.1.2","imagePullPolicy":"Always","name":"stork","resources":{"requests":{"cpu":"0.1"}}}],"hostPID":false,"serviceAccountName":"stork-account"}}}}
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: null
  generation: 1
  labels:
    tier: control-plane
  name: stork
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/stork
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 3
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      name: stork
      tier: control-plane
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      creationTimestamp: null
      labels:
        name: stork
        tier: control-plane
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - stork
            topologyKey: kubernetes.io/hostname
      containers:
      - command:
        - /stork
        - --driver=pxd
        - --verbose
        - --leader-elect=true
        - --health-monitor-interval=120
        image: openstorage/stork:2.1.2
        imagePullPolicy: Always
        name: stork
        resources:
          requests:
            cpu: 100m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: stork-account
      serviceAccountName: stork-account
      terminationGracePeriodSeconds: 30
status: {}
