apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"tier":"px-web-console"},"name":"px-lighthouse","namespace":"kube-system"},"spec":{"ports":[{"name":"http","port":80,"targetPort":80},{"name":"https","port":443,"targetPort":"https"}],"selector":{"tier":"px-web-console"},"type":"NodePort"}}
  creationTimestamp: null
  labels:
    tier: px-web-console
  name: px-lighthouse
  selfLink: /api/v1/namespaces/kube-system/services/px-lighthouse
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    tier: px-web-console
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
