apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"helm","name":"tiller"},"name":"tiller-deploy","namespace":"kube-system"},"spec":{"ports":[{"name":"tiller","port":44134,"targetPort":"tiller"}],"selector":{"app":"helm","name":"tiller"},"type":"ClusterIP"},"status":{"loadBalancer":{}}}
  creationTimestamp: null
  labels:
    app: helm
    name: tiller
  name: tiller-deploy
  selfLink: /api/v1/namespaces/kube-system/services/tiller-deploy
spec:
  ports:
  - name: tiller
    port: 44134
    protocol: TCP
    targetPort: tiller
  selector:
    app: helm
    name: tiller
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
