apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"stork-service","namespace":"kube-system"},"spec":{"ports":[{"port":8099,"protocol":"TCP","targetPort":8099}],"selector":{"name":"stork"}}}
  creationTimestamp: null
  name: stork-service
  selfLink: /api/v1/namespaces/kube-system/services/stork-service
spec:
  ports:
  - port: 8099
    protocol: TCP
    targetPort: 8099
  selector:
    name: stork
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
