apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","app.kubernetes.io/name":"metrics-server","kubernetes.io/cluster-service":"true"},"name":"metrics-server","namespace":"kube-system"},"spec":{"ports":[{"port":443,"protocol":"TCP","targetPort":"https"}],"selector":{"app.kubernetes.io/name":"metrics-server"}}}
  creationTimestamp: null
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app.kubernetes.io/name: metrics-server
    kubernetes.io/cluster-service: "true"
  name: metrics-server
  selfLink: /api/v1/namespaces/kube-system/services/metrics-server
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/name: metrics-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
