apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: adservice
  selfLink: /api/v1/namespaces/istio-hipstershop/services/adservice
spec:
  ports:
  - name: grpc
    port: 9555
    protocol: TCP
    targetPort: 9555
  selector:
    app: adservice
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
