apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: emailservice
  selfLink: /api/v1/namespaces/istio-hipstershop/services/emailservice
spec:
  ports:
  - name: grpc
    port: 5000
    protocol: TCP
    targetPort: 8080
  selector:
    app: emailservice
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
