apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: redis-cart
  selfLink: /api/v1/namespaces/istio-hipstershop/services/redis-cart
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-cart
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
