apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: shippingservice
  selfLink: /api/v1/namespaces/istio-hipstershop/services/shippingservice
spec:
  ports:
  - name: grpc
    port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: shippingservice
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
