apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: cartservice
  selfLink: /api/v1/namespaces/istio-hipstershop/services/cartservice
spec:
  ports:
  - name: grpc
    port: 7070
    protocol: TCP
    targetPort: 7070
  selector:
    app: cartservice
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
