apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: currencyservice
  selfLink: /api/v1/namespaces/istio-hipstershop/services/currencyservice
spec:
  ports:
  - name: grpc
    port: 7000
    protocol: TCP
    targetPort: 7000
  selector:
    app: currencyservice
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
