apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: frontend
  selfLink: /api/v1/namespaces/istio-hipstershop/services/frontend
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
