apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: checkoutservice
  selfLink: /api/v1/namespaces/istio-hipstershop/services/checkoutservice
spec:
  ports:
  - name: grpc
    port: 5050
    protocol: TCP
    targetPort: 5050
  selector:
    app: checkoutservice
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
