apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/portworx-volume
  creationTimestamp: null
  finalizers:
  - kubernetes.io/pvc-protection
  name: minio-pv-claim
  selfLink: /api/v1/namespaces/istio-demo/persistentvolumeclaims/minio-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: portworx-sc
  volumeMode: Filesystem
  volumeName: pvc-f7aa5eaf-a19b-11e9-be54-0017a47700b8
status: {}
