apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{"volume.beta.kubernetes.io/storage-class":"px-mssql-sc"},"name":"mssql-data","namespace":"istio-demo"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"5Gi"}}}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-class: px-mssql-sc
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/portworx-volume
  creationTimestamp: null
  finalizers:
  - kubernetes.io/pvc-protection
  name: mssql-data
  selfLink: /api/v1/namespaces/istio-demo/persistentvolumeclaims/mssql-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  volumeMode: Filesystem
  volumeName: pvc-70fa4896-a191-11e9-be54-0017a47700b8
status: {}
