apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/portworx-volume
  creationTimestamp: null
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: zk
  name: datadir-zk-0
  selfLink: /api/v1/namespaces/istio-demo/persistentvolumeclaims/datadir-zk-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: portworx-sc
  volumeMode: Filesystem
  volumeName: pvc-ea14acb5-a20a-11e9-9f25-0017a47700c0
status: {}
