apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/portworx-volume
  creationTimestamp: null
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: minio
    chart: minio-2.4.17
    heritage: Tiller
    release: argo
  name: argo-minio
  selfLink: /api/v1/namespaces/istio-demo/persistentvolumeclaims/argo-minio
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: portworx-sc
  volumeMode: Filesystem
  volumeName: pvc-699402f6-9cb2-11e9-be54-0017a47700b8
status: {}
