apiVersion: v1
data:
  mysql-password: cXJCMnBLMkl6Mw==
  mysql-root-password: b09Ja2EwQlJwaQ==
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: veering-tarsier-mysql
    chart: mysql-1.2.1
    heritage: Tiller
    release: veering-tarsier
  name: veering-tarsier-mysql
  selfLink: /api/v1/namespaces/istio-demo/secrets/veering-tarsier-mysql
type: Opaque
