apiVersion: v1
data:
  token: VFN0SlgwWDhYTDVwTUY4eXFRaGpMcU05ZDA4bU9xZk16VnV6aFJab2FnZklSeXJwbGY4Z0MzSkkzbGJSR3hKWiM=
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: shared-secrets
    chart: shared-secrets-0.1.0
    heritage: Tiller
    release: gitlab
  name: gitlab-gitaly-secret
  selfLink: /api/v1/namespaces/istio-demo/secrets/gitlab-gitaly-secret
type: Opaque
