apiVersion: v1
data:
  secret: ZW1sNmJ6VTNhSGw2ZEdsNGN6TTJhR05zTW1ZMWQyazRZblkzWjNaM2EzUjZjekptWVhCeU5HUnRaVE40WXpJNWNqZHFlbVpxYlhCag==
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: shared-secrets
    chart: shared-secrets-0.1.0
    heritage: Tiller
    release: gitlab
  name: gitlab-registry-httpsecret
  selfLink: /api/v1/namespaces/istio-demo/secrets/gitlab-registry-httpsecret
type: Opaque
