apiVersion: v1
data:
  shared_secret: VlRWUFZqUkdibmg0V1ZSa2NtcGlVbUpIU0dkSFFXdzRXa281VmtSRWVYaz0=
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: shared-secrets
    chart: shared-secrets-0.1.0
    heritage: Tiller
    release: gitlab
  name: gitlab-gitlab-workhorse-secret
  selfLink: /api/v1/namespaces/istio-demo/secrets/gitlab-gitlab-workhorse-secret
type: Opaque
