apiVersion: v1
data:
  accesskey: QUtJQUlPU0ZPRE5ON0VYQU1QTEU=
  secretkey: d0phbHJYVXRuRkVNSS9LN01ERU5HL2JQeFJmaUNZRVhBTVBMRUtFWQ==
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: minio
    chart: minio-2.4.17
    heritage: Tiller
    release: argo
  name: argo-minio
  selfLink: /api/v1/namespaces/istio-demo/secrets/argo-minio
type: Opaque
