apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"details","service":"details"},"name":"details","namespace":"istio-demo"},"spec":{"ports":[{"name":"http","port":9080}],"selector":{"app":"details"}}}
  creationTimestamp: null
  labels:
    app: details
    service: details
  name: details
  selfLink: /api/v1/namespaces/istio-demo/services/details
spec:
  ports:
  - name: http
    port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: details
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
