apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"ratings","service":"ratings"},"name":"ratings","namespace":"istio-demo"},"spec":{"ports":[{"name":"http","port":9080}],"selector":{"app":"ratings"}}}
  creationTimestamp: null
  labels:
    app: ratings
    service: ratings
  name: ratings
  selfLink: /api/v1/namespaces/istio-demo/services/ratings
spec:
  ports:
  - name: http
    port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: ratings
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
