all:
  hosts:
    k8s-r3-m1:
      ansible_host: 10.202.115.
      ip: 10.202.115.
      access_ip: 10.202.115.
    k8s-r3-m2:
      ansible_host: 10.202.115.
      ip: 10.202.115.
      access_ip: 10.202.115.
    k8s-r3-w1:
      ansible_host: 10.202.115.
      ip: 10.202.115.
      access_ip: 10.202.115.
    k8s-r3-w2:
      ansible_host: 10.202.115.
      ip: 10.202.115.
      access_ip: 10.202.115.
    k8s-r3-w3:
      ansible_host: 10.202.115.
      ip: 10.202.115.
      access_ip: 10.202.115.
  children:
    kube-master:
      hosts:
        k8s-r3-m1:
        k8s-r3-m2:
    kube-node:
      hosts:
        k8s-r3-w1:
        k8s-r3-w2:
        k8s-r3-w3:
    etcd:
      hosts:
        bay9:
        bay10:
        bay11:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
