all:
  hosts:
    k8s-prod-controller-0:
      ansible_host: 10.202.115.87
      ip: 10.202.115.87
      access_ip: 10.202.115.87
    k8s-prod-controller-1:
      ansible_host: 10.202.115.30
      ip: 10.202.115.30
      access_ip: 10.202.115.30
    k8s-prod-controller-2:
      ansible_host: 10.202.115.93
      ip: 10.202.115.93
      access_ip: 10.202.115.93
    k8s-prod-worker-0:
      ansible_host: 10.202.115.55
      ip: 10.202.115.55
      access_ip: 10.202.115.55
    k8s-prod-worker-1:
      ansible_host: 10.202.115.36
      ip: 10.202.115.36
      access_ip: 10.202.115.36
    k8s-prod-worker-2:
      ansible_host: 10.202.115.94
      ip: 10.202.115.94
      access_ip: 10.202.115.94
  children:
    kube-master:
      hosts:
        k8s-prod-controller-0:
        k8s-prod-controller-1:
        k8s-prod-controller-2:
    kube-node:
      hosts:
        k8s-prod-controller-0:
        k8s-prod-controller-1:
        k8s-prod-controller-2:
        k8s-prod-worker-0:
        k8s-prod-worker-1:
        k8s-prod-worker-2:
    etcd:
      hosts:
        k8s-prod-controller-0:
        k8s-prod-controller-1:
        k8s-prod-controller-2:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
