apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"name":"sleep","namespace":"foo"},"spec":{"replicas":1,"template":{"metadata":{"labels":{"app":"sleep"}},"spec":{"containers":[{"command":["/bin/sleep","3650d"],"image":"pstauffer/curl","imagePullPolicy":"IfNotPresent","name":"sleep"}],"serviceAccountName":"sleep"}}}}
  creationTimestamp: null
  generation: 1
  labels:
    app: sleep
  name: sleep
  selfLink: /apis/extensions/v1beta1/namespaces/foo/deployments/sleep
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: sleep
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sleep
    spec:
      containers:
      - command:
        - /bin/sleep
        - 3650d
        image: pstauffer/curl
        imagePullPolicy: IfNotPresent
        name: sleep
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: sleep
      serviceAccountName: sleep
      terminationGracePeriodSeconds: 30
status: {}
