apiVersion: v1
data:
  providers.yaml: |
    apiVersion: 1

    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /etc/grafana/dashboards
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: flagger-grafana-providers
  selfLink: /api/v1/namespaces/istio-system/configmaps/flagger-grafana-providers
