apiVersion: v1
data:
  config.yaml: "istio_namespace: istio-system\nserver:\n  port: 20001\nexternal_services:\n
    \ istio:\n    url_service_version: http://istio-pilot:8080/version\n  jaeger:\n
    \   url: \n  grafana:\n    url: \n"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.yaml":"istio_namespace: istio-system\nserver:\n  port: 20001\nexternal_services:\n  istio:\n    url_service_version: http://istio-pilot:8080/version\n  jaeger:\n    url: \n  grafana:\n    url: \n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"kiali","chart":"kiali","heritage":"Tiller","release":"istio"},"name":"kiali","namespace":"istio-system"}}
  creationTimestamp: null
  labels:
    app: kiali
    chart: kiali
    heritage: Tiller
    release: istio
  name: kiali
  selfLink: /api/v1/namespaces/istio-system/configmaps/kiali
