apiVersion: v1
data:
  crd-11.yaml: |-
    kind: CustomResourceDefinition
    apiVersion: apiextensions.k8s.io/v1beta1
    metadata:
      name: cloudwatches.config.istio.io
      labels:
        app: mixer
        package: cloudwatch
        istio: mixer-adapter
      annotations:
        "helm.sh/resource-policy": keep
    spec:
      group: config.istio.io
      names:
        kind: cloudwatch
        plural: cloudwatches
        singular: cloudwatch
        categories:
        - istio-io
        - policy-istio-io
      scope: Namespaced
      version: v1alpha2
    ---
    kind: CustomResourceDefinition
    apiVersion: apiextensions.k8s.io/v1beta1
    metadata:
      name: dogstatsds.config.istio.io
      labels:
        app: mixer
        package: dogstatsd
        istio: mixer-adapter
      annotations:
        "helm.sh/resource-policy": keep
    spec:
      group: config.istio.io
      names:
        kind: dogstatsd
        plural: dogstatsds
        singular: dogstatsd
        categories:
        - istio-io
        - policy-istio-io
      scope: Namespaced
      version: v1alpha2
    ---
    apiVersion: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    metadata:
      name: sidecars.networking.istio.io
      labels:
        app: istio-pilot
        chart: istio
        heritage: Tiller
        release: istio
      annotations:
        "helm.sh/resource-policy": keep
    spec:
      group: networking.istio.io
      names:
        kind: Sidecar
        plural: sidecars
        singular: sidecar
        categories:
        - istio-io
        - networking-istio-io
      scope: Namespaced
      version: v1alpha3
    ---
    kind: CustomResourceDefinition
    apiVersion: apiextensions.k8s.io/v1beta1
    metadata:
      name: zipkins.config.istio.io
      labels:
        app: mixer
        package: zipkin
        istio: mixer-adapter
      annotations:
        "helm.sh/resource-policy": keep
    spec:
      group: config.istio.io
      names:
        kind: zipkin
        plural: zipkins
        singular: zipkin
        categories:
        - istio-io
        - policy-istio-io
      scope: Namespaced
      version: v1alpha2
    ---
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"crd-11.yaml":"kind: CustomResourceDefinition\napiVersion: apiextensions.k8s.io/v1beta1\nmetadata:\n  name: cloudwatches.config.istio.io\n  labels:\n    app: mixer\n    package: cloudwatch\n    istio: mixer-adapter\n  annotations:\n    \"helm.sh/resource-policy\": keep\nspec:\n  group: config.istio.io\n  names:\n    kind: cloudwatch\n    plural: cloudwatches\n    singular: cloudwatch\n    categories:\n    - istio-io\n    - policy-istio-io\n  scope: Namespaced\n  version: v1alpha2\n---\nkind: CustomResourceDefinition\napiVersion: apiextensions.k8s.io/v1beta1\nmetadata:\n  name: dogstatsds.config.istio.io\n  labels:\n    app: mixer\n    package: dogstatsd\n    istio: mixer-adapter\n  annotations:\n    \"helm.sh/resource-policy\": keep\nspec:\n  group: config.istio.io\n  names:\n    kind: dogstatsd\n    plural: dogstatsds\n    singular: dogstatsd\n    categories:\n    - istio-io\n    - policy-istio-io\n  scope: Namespaced\n  version: v1alpha2\n---\napiVersion: apiextensions.k8s.io/v1beta1\nkind: CustomResourceDefinition\nmetadata:\n  name: sidecars.networking.istio.io\n  labels:\n    app: istio-pilot\n    chart: istio\n    heritage: Tiller\n    release: istio\n  annotations:\n    \"helm.sh/resource-policy\": keep\nspec:\n  group: networking.istio.io\n  names:\n    kind: Sidecar\n    plural: sidecars\n    singular: sidecar\n    categories:\n    - istio-io\n    - networking-istio-io\n  scope: Namespaced\n  version: v1alpha3\n---\nkind: CustomResourceDefinition\napiVersion: apiextensions.k8s.io/v1beta1\nmetadata:\n  name: zipkins.config.istio.io\n  labels:\n    app: mixer\n    package: zipkin\n    istio: mixer-adapter\n  annotations:\n    \"helm.sh/resource-policy\": keep\nspec:\n  group: config.istio.io\n  names:\n    kind: zipkin\n    plural: zipkins\n    singular: zipkin\n    categories:\n    - istio-io\n    - policy-istio-io\n  scope: Namespaced\n  version: v1alpha2\n---"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"istio-crd-11","namespace":"istio-system"}}
  creationTimestamp: null
  name: istio-crd-11
  selfLink: /api/v1/namespaces/istio-system/configmaps/istio-crd-11
