apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"sidecarInjectorWebhook","chart":"sidecarInjectorWebhook","heritage":"Tiller","istio":"sidecar-injector","release":"istio"},"name":"istio-sidecar-injector","namespace":"istio-system"},"spec":{"replicas":1,"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":0}},"template":{"metadata":{"annotations":{"sidecar.istio.io/inject":"false"},"labels":{"app":"sidecarInjectorWebhook","chart":"sidecarInjectorWebhook","heritage":"Tiller","istio":"sidecar-injector","release":"istio"}},"spec":{"affinity":{"nodeAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"preference":{"matchExpressions":[{"key":"beta.kubernetes.io/arch","operator":"In","values":["amd64"]}]},"weight":2},{"preference":{"matchExpressions":[{"key":"beta.kubernetes.io/arch","operator":"In","values":["ppc64le"]}]},"weight":2},{"preference":{"matchExpressions":[{"key":"beta.kubernetes.io/arch","operator":"In","values":["s390x"]}]},"weight":2}],"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"beta.kubernetes.io/arch","operator":"In","values":["amd64","ppc64le","s390x"]}]}]}}},"containers":[{"args":["--caCertFile=/etc/istio/certs/root-cert.pem","--tlsCertFile=/etc/istio/certs/cert-chain.pem","--tlsKeyFile=/etc/istio/certs/key.pem","--injectConfig=/etc/istio/inject/config","--meshConfig=/etc/istio/config/mesh","--healthCheckInterval=2s","--healthCheckFile=/health"],"image":"docker.io/istio/sidecar_injector:1.1.9","imagePullPolicy":"IfNotPresent","livenessProbe":{"exec":{"command":["/usr/local/bin/sidecar-injector","probe","--probe-path=/health","--interval=4s"]},"initialDelaySeconds":4,"periodSeconds":4},"name":"sidecar-injector-webhook","readinessProbe":{"exec":{"command":["/usr/local/bin/sidecar-injector","probe","--probe-path=/health","--interval=4s"]},"initialDelaySeconds":4,"periodSeconds":4},"resources":{"requests":{"cpu":"10m"}},"volumeMounts":[{"mountPath":"/etc/istio/config","name":"config-volume","readOnly":true},{"mountPath":"/etc/istio/certs","name":"certs","readOnly":true},{"mountPath":"/etc/istio/inject","name":"inject-config","readOnly":true}]}],"serviceAccountName":"istio-sidecar-injector-service-account","volumes":[{"configMap":{"name":"istio"},"name":"config-volume"},{"name":"certs","secret":{"secretName":"istio.istio-sidecar-injector-service-account"}},{"configMap":{"items":[{"key":"config","path":"config"}],"name":"istio-sidecar-injector"},"name":"inject-config"}]}}}}
  creationTimestamp: null
  generation: 1
  labels:
    app: sidecarInjectorWebhook
    chart: sidecarInjectorWebhook
    heritage: Tiller
    istio: sidecar-injector
    release: istio
  name: istio-sidecar-injector
  selfLink: /apis/extensions/v1beta1/namespaces/istio-system/deployments/istio-sidecar-injector
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: sidecarInjectorWebhook
      chart: sidecarInjectorWebhook
      heritage: Tiller
      istio: sidecar-injector
      release: istio
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        app: sidecarInjectorWebhook
        chart: sidecarInjectorWebhook
        heritage: Tiller
        istio: sidecar-injector
        release: istio
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
            weight: 2
          - preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - ppc64le
            weight: 2
          - preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - s390x
            weight: 2
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
      containers:
      - args:
        - --caCertFile=/etc/istio/certs/root-cert.pem
        - --tlsCertFile=/etc/istio/certs/cert-chain.pem
        - --tlsKeyFile=/etc/istio/certs/key.pem
        - --injectConfig=/etc/istio/inject/config
        - --meshConfig=/etc/istio/config/mesh
        - --healthCheckInterval=2s
        - --healthCheckFile=/health
        image: docker.io/istio/sidecar_injector:1.1.9
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/sidecar-injector
            - probe
            - --probe-path=/health
            - --interval=4s
          failureThreshold: 3
          initialDelaySeconds: 4
          periodSeconds: 4
          successThreshold: 1
          timeoutSeconds: 1
        name: sidecar-injector-webhook
        readinessProbe:
          exec:
            command:
            - /usr/local/bin/sidecar-injector
            - probe
            - --probe-path=/health
            - --interval=4s
          failureThreshold: 3
          initialDelaySeconds: 4
          periodSeconds: 4
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 10m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/istio/config
          name: config-volume
          readOnly: true
        - mountPath: /etc/istio/certs
          name: certs
          readOnly: true
        - mountPath: /etc/istio/inject
          name: inject-config
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: istio-sidecar-injector-service-account
      serviceAccountName: istio-sidecar-injector-service-account
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: istio
        name: config-volume
      - name: certs
        secret:
          defaultMode: 420
          secretName: istio.istio-sidecar-injector-service-account
      - configMap:
          defaultMode: 420
          items:
          - key: config
            path: config
          name: istio-sidecar-injector
        name: inject-config
status: {}
