apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"autoscaling/v2beta1","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"labels":{"app":"egressgateway","chart":"gateways","heritage":"Tiller","release":"istio"},"name":"istio-egressgateway","namespace":"istio-system"},"spec":{"maxReplicas":5,"metrics":[{"resource":{"name":"cpu","targetAverageUtilization":80},"type":"Resource"}],"minReplicas":1,"scaleTargetRef":{"apiVersion":"apps/v1beta1","kind":"Deployment","name":"istio-egressgateway"}}}
  creationTimestamp: null
  labels:
    app: egressgateway
    chart: gateways
    heritage: Tiller
    release: istio
  name: istio-egressgateway
  selfLink: /apis/autoscaling/v1/namespaces/istio-system/horizontalpodautoscalers/istio-egressgateway
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: istio-egressgateway
  targetCPUUtilizationPercentage: 80
status:
  currentReplicas: 0
  desiredReplicas: 0
