apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"batch/v1","kind":"Job","metadata":{"annotations":{},"name":"istio-init-crd-11","namespace":"istio-system"},"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject":"false"}},"spec":{"containers":[{"command":["kubectl","apply","-f","/etc/istio/crd-11/crd-11.yaml"],"image":"docker.io/istio/kubectl:1.1.9","imagePullPolicy":"IfNotPresent","name":"istio-init-crd-11","volumeMounts":[{"mountPath":"/etc/istio/crd-11","name":"crd-11","readOnly":true}]}],"restartPolicy":"OnFailure","serviceAccountName":"istio-init-service-account","volumes":[{"configMap":{"name":"istio-crd-11"},"name":"crd-11"}]}}}}
  creationTimestamp: null
  labels:
    controller-uid: b9399cc3-97d0-11e9-96f3-0017a47700b8
    job-name: istio-init-crd-11
  name: istio-init-crd-11
  selfLink: /apis/batch/v1/namespaces/istio-system/jobs/istio-init-crd-11
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: b9399cc3-97d0-11e9-96f3-0017a47700b8
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        controller-uid: b9399cc3-97d0-11e9-96f3-0017a47700b8
        job-name: istio-init-crd-11
    spec:
      containers:
      - command:
        - kubectl
        - apply
        - -f
        - /etc/istio/crd-11/crd-11.yaml
        image: docker.io/istio/kubectl:1.1.9
        imagePullPolicy: IfNotPresent
        name: istio-init-crd-11
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/istio/crd-11
          name: crd-11
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: istio-init-service-account
      serviceAccountName: istio-init-service-account
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: istio-crd-11
        name: crd-11
status: {}
