apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"batch/v1","kind":"Job","metadata":{"annotations":{"helm.sh/hook":"post-delete","helm.sh/hook-delete-policy":"hook-succeeded","helm.sh/hook-weight":"3"},"labels":{"app":"security","chart":"security","heritage":"Tiller","release":"istio"},"name":"istio-cleanup-secrets-1.1.9","namespace":"istio-system"},"spec":{"template":{"metadata":{"labels":{"app":"security","chart":"security","heritage":"Tiller","release":"istio"},"name":"istio-cleanup-secrets"},"spec":{"affinity":{"nodeAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"preference":{"matchExpressions":[{"key":"beta.kubernetes.io/arch","operator":"In","values":["amd64"]}]},"weight":2},{"preference":{"matchExpressions":[{"key":"beta.kubernetes.io/arch","operator":"In","values":["ppc64le"]}]},"weight":2},{"preference":{"matchExpressions":[{"key":"beta.kubernetes.io/arch","operator":"In","values":["s390x"]}]},"weight":2}],"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"beta.kubernetes.io/arch","operator":"In","values":["amd64","ppc64le","s390x"]}]}]}}},"containers":[{"command":["/bin/bash","-c","kubectl get secret --all-namespaces | grep \"istio.io/key-and-cert\" |  while read -r entry; do\n  ns=$(echo $entry | awk '{print $1}');\n  name=$(echo $entry | awk '{print $2}');\n  kubectl delete secret $name -n $ns;\ndone\n"],"image":"docker.io/istio/kubectl:1.1.9","imagePullPolicy":"IfNotPresent","name":"kubectl"}],"restartPolicy":"OnFailure","serviceAccountName":"istio-cleanup-secrets-service-account"}}}}
  creationTimestamp: null
  labels:
    app: security
    chart: security
    heritage: Tiller
    release: istio
  name: istio-cleanup-secrets-1.1.9
  selfLink: /apis/batch/v1/namespaces/istio-system/jobs/istio-cleanup-secrets-1.1.9
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 36da3104-93f5-11e9-96f3-0017a47700b8
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: security
        chart: security
        controller-uid: 36da3104-93f5-11e9-96f3-0017a47700b8
        heritage: Tiller
        job-name: istio-cleanup-secrets-1.1.9
        release: istio
      name: istio-cleanup-secrets
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
            weight: 2
          - preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - ppc64le
            weight: 2
          - preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - s390x
            weight: 2
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
      containers:
      - command:
        - /bin/bash
        - -c
        - |
          kubectl get secret --all-namespaces | grep "istio.io/key-and-cert" |  while read -r entry; do
            ns=$(echo $entry | awk '{print $1}');
            name=$(echo $entry | awk '{print $2}');
            kubectl delete secret $name -n $ns;
          done
        image: docker.io/istio/kubectl:1.1.9
        imagePullPolicy: IfNotPresent
        name: kubectl
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: istio-cleanup-secrets-service-account
      serviceAccountName: istio-cleanup-secrets-service-account
      terminationGracePeriodSeconds: 30
status: {}
