apiVersion: v1
data:
  passphrase: YWRtaW4=
  username: YWRtaW4=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"passphrase":"YWRtaW4=","username":"YWRtaW4="},"kind":"Secret","metadata":{"annotations":{},"labels":{"app":"kiali","chart":"kiali","heritage":"Tiller","release":"istio"},"name":"kiali","namespace":"istio-system"},"type":"Opaque"}
  creationTimestamp: null
  labels:
    app: kiali
    chart: kiali
    heritage: Tiller
    release: istio
  name: kiali
  selfLink: /api/v1/namespaces/istio-system/secrets/kiali
type: Opaque
