apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: grafana
    chart: grafana-1.2.0
    heritage: Tiller
    release: flagger-grafana
  name: flagger-grafana
  selfLink: /api/v1/namespaces/istio-system/services/flagger-grafana
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: flagger-grafana
    release: flagger-grafana
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
