apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"galley","chart":"galley","heritage":"Tiller","istio":"galley","release":"istio"},"name":"istio-galley","namespace":"istio-system"},"spec":{"ports":[{"name":"https-validation","port":443},{"name":"http-monitoring","port":15014},{"name":"grpc-mcp","port":9901}],"selector":{"istio":"galley"}}}
  creationTimestamp: null
  labels:
    app: galley
    chart: galley
    heritage: Tiller
    istio: galley
    release: istio
  name: istio-galley
  selfLink: /api/v1/namespaces/istio-system/services/istio-galley
spec:
  ports:
  - name: https-validation
    port: 443
    protocol: TCP
    targetPort: 443
  - name: http-monitoring
    port: 15014
    protocol: TCP
    targetPort: 15014
  - name: grpc-mcp
    port: 9901
    protocol: TCP
    targetPort: 9901
  selector:
    istio: galley
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
