apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"kiali-lb","namespace":"istio-system"},"spec":{"ports":[{"name":"kiali","port":20001,"protocol":"TCP","targetPort":20001}],"selector":{"app":"kiali"},"type":"LoadBalancer"}}
  creationTimestamp: null
  name: kiali-lb
  selfLink: /api/v1/namespaces/istio-system/services/kiali-lb
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: kiali
    nodePort: 30529
    port: 20001
    protocol: TCP
    targetPort: 20001
  selector:
    app: kiali
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
