apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"prometheus.io/scrape":"true"},"labels":{"name":"prometheus"},"name":"prometheus","namespace":"istio-system"},"spec":{"ports":[{"name":"http-prometheus","port":9090,"protocol":"TCP"}],"selector":{"app":"prometheus"}}}
    prometheus.io/scrape: "true"
  creationTimestamp: null
  labels:
    name: prometheus
  name: prometheus
  selfLink: /api/v1/namespaces/istio-system/services/prometheus
spec:
  ports:
  - name: http-prometheus
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
