apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"prometheus-kiali-lb","namespace":"istio-system"},"spec":{"ports":[{"name":"grafana","port":3000,"protocol":"TCP","targetPort":3000}],"selector":{"app":"grafana"},"type":"LoadBalancer"}}
  creationTimestamp: null
  name: prometheus-kiali-lb
  selfLink: /api/v1/namespaces/istio-system/services/prometheus-kiali-lb
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: grafana
    nodePort: 30776
    port: 3000
    protocol: TCP
    targetPort: 3000
  - name: prometheus
    nodePort: 31183
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: grafana
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
