apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"jaeger","chart":"tracing","heritage":"Tiller","jaeger-infra":"jaeger-service","release":"istio"},"name":"jaeger-query","namespace":"istio-system"},"spec":{"ports":[{"name":"query-http","port":16686,"protocol":"TCP","targetPort":16686}],"selector":{"app":"jaeger"}}}
  creationTimestamp: null
  labels:
    app: jaeger
    chart: tracing
    heritage: Tiller
    jaeger-infra: jaeger-service
    release: istio
  name: jaeger-query
  selfLink: /api/v1/namespaces/istio-system/services/jaeger-query
spec:
  ports:
  - name: query-http
    port: 16686
    protocol: TCP
    targetPort: 16686
  selector:
    app: jaeger
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
