apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"grafana","chart":"grafana","heritage":"Tiller","release":"istio"},"name":"grafana","namespace":"istio-system"},"spec":{"ports":[{"name":"http","port":3000,"protocol":"TCP","targetPort":3000}],"selector":{"app":"grafana"},"type":"ClusterIP"}}
  creationTimestamp: null
  labels:
    app: grafana
    chart: grafana
    heritage: Tiller
    release: istio
  name: grafana
  selfLink: /api/v1/namespaces/istio-system/services/grafana
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 32167
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
