apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"security","chart":"security","heritage":"Tiller","istio":"citadel","release":"istio"},"name":"istio-citadel","namespace":"istio-system"},"spec":{"ports":[{"name":"grpc-citadel","port":8060,"protocol":"TCP","targetPort":8060},{"name":"http-monitoring","port":15014}],"selector":{"istio":"citadel"},"type":"LoadBalancer"}}
  creationTimestamp: null
  labels:
    app: security
    chart: security
    heritage: Tiller
    istio: citadel
    release: istio
  name: istio-citadel
  selfLink: /api/v1/namespaces/istio-system/services/istio-citadel
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: grpc-citadel
    nodePort: 30810
    port: 8060
    protocol: TCP
    targetPort: 8060
  - name: http-monitoring
    nodePort: 30629
    port: 15014
    protocol: TCP
    targetPort: 15014
  selector:
    istio: citadel
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
