apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"jaeger","chart":"tracing","heritage":"Tiller","release":"istio"},"name":"zipkin","namespace":"istio-system"},"spec":{"ports":[{"name":"http","port":9411,"protocol":"TCP","targetPort":9411}],"selector":{"app":"jaeger"},"type":"ClusterIP"}}
  creationTimestamp: null
  labels:
    app: jaeger
    chart: tracing
    heritage: Tiller
    release: istio
  name: zipkin
  selfLink: /api/v1/namespaces/istio-system/services/zipkin
spec:
  ports:
  - name: http
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    app: jaeger
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
