apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"pilot","chart":"pilot","heritage":"Tiller","istio":"pilot","release":"istio"},"name":"istio-pilot","namespace":"istio-system"},"spec":{"ports":[{"name":"grpc-xds","port":15010},{"name":"https-xds","port":15011},{"name":"http-legacy-discovery","port":8080},{"name":"http-monitoring","port":15014}],"selector":{"istio":"pilot"},"type":"LoadBalancer"}}
  creationTimestamp: null
  labels:
    app: pilot
    chart: pilot
    heritage: Tiller
    istio: pilot
    release: istio
  name: istio-pilot
  selfLink: /api/v1/namespaces/istio-system/services/istio-pilot
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: grpc-xds
    nodePort: 31432
    port: 15010
    protocol: TCP
    targetPort: 15010
  - name: https-xds
    nodePort: 30526
    port: 15011
    protocol: TCP
    targetPort: 15011
  - name: http-legacy-discovery
    nodePort: 31257
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: http-monitoring
    nodePort: 30881
    port: 15014
    protocol: TCP
    targetPort: 15014
  selector:
    istio: pilot
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
