apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: portworx-volume-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/portworx-volume
  creationTimestamp: null
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-70fa4896-a191-11e9-be54-0017a47700b8
  selfLink: /api/v1/persistentvolumes/pvc-70fa4896-a191-11e9-be54-0017a47700b8
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 15Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: mssql-data
    namespace: istio-demo
    resourceVersion: "5224792"
    uid: 70fa4896-a191-11e9-be54-0017a47700b8
  persistentVolumeReclaimPolicy: Delete
  portworxVolume:
    volumeID: "621607079026871304"
  storageClassName: px-mssql-sc
  volumeMode: Filesystem
status: {}
