apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: portworx-volume-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/portworx-volume
  creationTimestamp: null
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-ea14acb5-a20a-11e9-9f25-0017a47700c0
  selfLink: /api/v1/persistentvolumes/pvc-ea14acb5-a20a-11e9-9f25-0017a47700c0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: datadir-zk-0
    namespace: istio-demo
    resourceVersion: "5384388"
    uid: ea14acb5-a20a-11e9-9f25-0017a47700c0
  persistentVolumeReclaimPolicy: Delete
  portworxVolume:
    volumeID: "495757296577589816"
  storageClassName: portworx-sc
  volumeMode: Filesystem
status: {}
