apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: portworx-volume-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/portworx-volume
  creationTimestamp: null
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-9b2c7d59-a19d-11e9-be54-0017a47700b8
  selfLink: /api/v1/persistentvolumes/pvc-9b2c7d59-a19d-11e9-be54-0017a47700b8
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: postgres-data
    namespace: istio-demo
    resourceVersion: "5241069"
    uid: 9b2c7d59-a19d-11e9-be54-0017a47700b8
  persistentVolumeReclaimPolicy: Delete
  portworxVolume:
    volumeID: "947867444179802085"
  storageClassName: px-postgres-sc
  volumeMode: Filesystem
status: {}
