apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: portworx-volume-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/portworx-volume
  creationTimestamp: null
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-533ddd3e-a195-11e9-9f25-0017a47700c0
  selfLink: /api/v1/persistentvolumes/pvc-533ddd3e-a195-11e9-9f25-0017a47700c0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: cassandra-data-cassandra-0
    namespace: istio-demo
    resourceVersion: "5229999"
    uid: 533ddd3e-a195-11e9-9f25-0017a47700c0
  persistentVolumeReclaimPolicy: Delete
  portworxVolume:
    volumeID: "860603920894134749"
  storageClassName: px-storageclass
  volumeMode: Filesystem
status: {}
