apiVersion: v1
data:
  map-hash-bucket-size: "128"
  ssl-protocols: SSLv2
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"map-hash-bucket-size":"128","ssl-protocols":"SSLv2"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"ingress-nginx","app.kubernetes.io/part-of":"ingress-nginx"},"name":"ingress-nginx","namespace":"ingress-nginx"}}
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  name: ingress-nginx
  selfLink: /api/v1/namespaces/ingress-nginx/configmaps/ingress-nginx
