apiVersion: v1
data:
  alertmanager.yml: |
    global: {}
    receivers:
    - name: default-receiver
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: default-receiver
      repeat_interval: 3h
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: prometheus
    chart: prometheus-8.11.0
    component: alertmanager
    heritage: Tiller
    release: kubecost
  name: kubecost-prometheus-alertmanager
  selfLink: /api/v1/namespaces/kubecost/configmaps/kubecost-prometheus-alertmanager
