apiVersion: v1
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [auth.anonymous]
    enabled = true
    org_name = Main Org.
    org_role = Admin
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana
    - access: proxy
      isDefault: true
      name: Prometheus
      type: prometheus
      url: http://kubecost-prometheus-server.kubecost.svc.cluster.local
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: grafana
    chart: grafana-1.17.2
    heritage: Tiller
    release: kubecost
  name: kubecost-grafana
  selfLink: /api/v1/namespaces/kubecost/configmaps/kubecost-grafana
