apiVersion: v1
data:
  nginx.conf: "gzip_static  on;\n\nupstream api {\n    server kubecost-cost-analyzer.kubecost:9001;\n}\n\nupstream
    model {\n    server kubecost-cost-analyzer.kubecost:9003;\n}\nupstream grafana
    {\n    server kubecost-grafana.kubecost;\n\n}\n\n\nserver {\n    listen 9090;\n
    \   server_name _;\n    root /var/www;\n    index index.html;\n    add_header
    Cache-Control \"no-cache\";\n    add_header ETag \"1.32.0\";\n    location /api/
    {\n        proxy_pass http://api/;\n        proxy_redirect off;\n        proxy_http_version
    1.1;\n        proxy_set_header Connection \"\";\n        proxy_set_header  X-Real-IP
    \ $remote_addr;\n        proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;\n
    \   }\n    location /model/ {       \t\n        proxy_connect_timeout       180;\n
    \       proxy_send_timeout          180;\n        proxy_read_timeout          180;\n
    \       proxy_pass http://model/;\n        proxy_redirect off;\n        proxy_http_version
    1.1;\n        proxy_set_header Connection \"\";\n        proxy_set_header  X-Real-IP
    \ $remote_addr;\n        proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;\n
    \   }\n    location /grafana/ {\n        proxy_pass http://grafana/;\n        proxy_redirect
    off;\n        proxy_http_version 1.1;\n        proxy_set_header Connection \"\";\n
    \       proxy_set_header  X-Real-IP  $remote_addr;\n        proxy_set_header  X-Forwarded-For
    $proxy_add_x_forwarded_for;\n    }\n\n}\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: cost-analyzer
    app.kubernetes.io/instance: kubecost
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: cost-analyzer
    helm.sh/chart: cost-analyzer-1.32.0
  name: nginx-conf
  selfLink: /api/v1/namespaces/kubecost/configmaps/nginx-conf
