apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: prometheus
    chart: prometheus-8.11.0
    component: kube-state-metrics
    heritage: Tiller
    release: kubecost
  name: kubecost-prometheus-kube-state-metrics
  selfLink: /apis/extensions/v1beta1/namespaces/kubecost/deployments/kubecost-prometheus-kube-state-metrics
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: prometheus
      component: kube-state-metrics
      release: kubecost
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus
        chart: prometheus-8.11.0
        component: kube-state-metrics
        heritage: Tiller
        release: kubecost
    spec:
      containers:
      - image: quay.io/coreos/kube-state-metrics:v1.6.0
        imagePullPolicy: IfNotPresent
        name: prometheus-kube-state-metrics
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kubecost-prometheus-kube-state-metrics
      serviceAccountName: kubecost-prometheus-kube-state-metrics
      terminationGracePeriodSeconds: 30
status: {}
