apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: prometheus
    chart: prometheus-8.11.0
    component: pushgateway
    heritage: Tiller
    release: kubecost
  name: kubecost-prometheus-pushgateway
  selfLink: /apis/extensions/v1beta1/namespaces/kubecost/deployments/kubecost-prometheus-pushgateway
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: prometheus
      component: pushgateway
      release: kubecost
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus
        chart: prometheus-8.11.0
        component: pushgateway
        heritage: Tiller
        release: kubecost
    spec:
      containers:
      - image: prom/pushgateway:v0.6.0
        imagePullPolicy: IfNotPresent
        name: prometheus-pushgateway
        ports:
        - containerPort: 9091
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /#/status
            port: 9091
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: storage-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kubecost-prometheus-pushgateway
      serviceAccountName: kubecost-prometheus-pushgateway
      terminationGracePeriodSeconds: 30
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: kubecost-prometheus-pushgateway
status: {}
