apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  labels:
    job-name: cost-analyzer-checks-1563342600
  name: cost-analyzer-checks-1563342600
  ownerReferences:
  - apiVersion: batch/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: CronJob
    name: cost-analyzer-checks
  selfLink: /apis/batch/v1/namespaces/kubecost/jobs/cost-analyzer-checks-1563342600
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
  template:
    metadata:
      creationTimestamp: null
      labels:
        job-name: cost-analyzer-checks-1563342600
    spec:
      containers:
      - args:
        - node
        - ./node/cron.js
        env:
        - name: COST_ANALYZER_SERVER_ENDPOINT
          value: kubecost-cost-analyzer.kubecost.svc.cluster.local:9001
        - name: COST_ANALYZER_MODEL_ENDPOINT
          value: kubecost-cost-analyzer.kubecost.svc.cluster.local:9003
        - name: PROMETHEUS_ALERTMANAGER_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: prometheus-alertmanager-endpoint
              name: kubecost-cost-analyzer
        image: ajaytripathy/kubecost-checks:prod-1.32.0
        imagePullPolicy: IfNotPresent
        name: cost-analyzer-checks
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 20m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
