apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: prometheus
    chart: prometheus-8.11.0
    component: alertmanager
    heritage: Tiller
    release: kubecost
  name: kubecost-prometheus-alertmanager
  selfLink: /api/v1/namespaces/kubecost/persistentvolumeclaims/kubecost-prometheus-alertmanager
  annotations:
    volume.beta.kubernetes.io/storage-class: portworx-sc
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/portworx-volume
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
status: {}
