apiVersion: v1
data:
  admin-password: TXlQcktvNmNmMWMyQ0RONDJ5d1o0eGpmUkd5a3AyWTJhaFVuZFhCMg==
  admin-user: YWRtaW4=
  ldap-toml: ""
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: grafana
    chart: grafana-1.17.2
    heritage: Tiller
    release: kubecost
  name: kubecost-grafana
  selfLink: /api/v1/namespaces/kubecost/secrets/kubecost-grafana
type: Opaque
