apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: prometheus
    chart: prometheus-8.11.0
    component: alertmanager
    heritage: Tiller
    release: kubecost
  name: kubecost-prometheus-alertmanager
  selfLink: /api/v1/namespaces/kubecost/services/kubecost-prometheus-alertmanager
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9093
  selector:
    app: prometheus
    component: alertmanager
    release: kubecost
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
