apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  creationTimestamp: null
  labels:
    app: prometheus
    chart: prometheus-8.11.0
    component: kube-state-metrics
    heritage: Tiller
    release: kubecost
  name: kubecost-prometheus-kube-state-metrics
  selfLink: /api/v1/namespaces/kubecost/services/kubecost-prometheus-kube-state-metrics
spec:
  clusterIP: None
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: prometheus
    component: kube-state-metrics
    release: kubecost
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
