apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: grafana
    chart: grafana-1.17.2
    heritage: Tiller
    release: kubecost
  name: kubecost-grafana
  selfLink: /api/v1/namespaces/kubecost/services/kubecost-grafana
spec:
  ports:
  - name: service
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
    release: kubecost
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
