apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: prometheus
    chart: prometheus-8.11.0
    component: server
    heritage: Tiller
    release: kubecost
  name: kubecost-prometheus-server
  selfLink: /api/v1/namespaces/kubecost/services/kubecost-prometheus-server
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
    component: server
    release: kubecost
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
